//
// This header file is auto generated by update_git_info.sh
// for updating informations related with OME git repository.
//
#pragma once

#define OME_GIT_VERSION                    ""
#define OME_GIT_VERSION_EXTRA              ""